sudo: required
dist: trusty
language: node_js
node_js:
- '6'
cache:
  bundler: true
  directories:
  - node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install -g codecov
- npm install
script:
- npm run test:travis
- npm run integration:travis
- npm run eslint
after_success:
- npm run codecov
notifications:
  slack:
    secure: d5AQcOtE64iRta7beecYMeHWsyo9CRp8Wgt7gSsotMFFzMvkgwN1ZA981sVoaPdISxUntxktoEtCcrSdQgN5Ya6NcY4EAgnb+FBki8174VjGUHsSfW8gkeVKCIdd8vWGQagunrG/FVU3PRadgmhFTDPuSfFTYxnU+OHROPbncSQpF5rZblw16XQ0MVksGSbHIHza6wcPyfknk+2dqWrMPeHANpuVOrP5uiC8gFt1nIAYLmLHtsPro7csLN/VYQYWCQjJVzLE7B/E+q3suNBw0mV38XYMz9gHBCy7OQjIHB+UUEgO7ch4anfAF+NEmxGbyO7rInGDpPJaOxtcAQKNTEgUi9YZNm36Kdde7xvix1/ExAblgSBNug/4a1QPctfp6PWPAXNsTJoFkm0wVjWYT+FmKLvjYDJoJp6v2xBlOdh7x8AQuZC8HhiKisTJfkvrGx0UGTIFQdYbk1XB44jOI/t45IDN6My73FtqArc2wEZB2ZGMk83ExZ1XcPoRoA22hxOeQdSE1xWcAiaCq6zsd6YkJiRNEkw7aTZ3LH+tZ6y2pQJYlykYfEW4HRFkgRQoRXTLX+02WBTyvqVEKxbDX5p9Ee4N8eWBYU/TBkUdgOr+HyyleTCl4H+CXm/jctNNh7FAEBHlNdIzh8P1O/a1/71NUHgxRsnXyOd1xXsUYy4=
before_deploy: npm version from-git
deploy:
  provider: npm
  email: accounts@hyphe.me
  api_key:
    secure: pKcFbnkf92SpOP7Dvfmaw0zPmYcT2tACMt4GYQr6+4mRIi8c+OtZvfHHN/hS43cLL7FOQcMuBp3Z6iAk4tAxQ+dj06RNJ1eP5Bxg6uk2Q/oB8R56BgA4Rkv6XbgzoIq7yL/PhbzjmVY4bOuTs63aZljFoLtK/6MJgMyZ+ctn4G8H8JbfwguVu/ezM0Q0LwYQJWkv8iaur+c0BRZ5hc7xx3tP3i2/cts+xD3lLiXJI6yFXYpsL43kwo6KuZs7SU1nAaJRrvOb4ZOCtPqzbVFHe2tCz+zJayHpjuVZMC5D6IwZ2qb3NPDRzs7PdWO8tMEdnXbJWOjINgqtht+zBCrYqJhRNwk8w1f4G8MKXGv7PwrDrXNmKBIOzQG6x8VDc4tX8w2ywaPB2Ogqyf7qEXKJoq5syEeEEVU551WRnFWPvj5+MS32IINdS3fqGJNDGGOw5Dv4jsfJ0H3v/69AnWXQEJ9b1afAVzsO9TyciNdvojsAli92wYXBGhSwGP78tCFcgvNGlFLGeA9O4wR22p3PXNfbL77v9zmWW2elKq+DE+E4FL1xwm74JbMun1KyfnHk8oP9khjJL/PtZUp2PwbIZ3tQg5lt70uUg5iMJNRaydKP30GgorxNORCtbAofVGFbslA9Ix8F4QCr9ubAUA53sBBQ9LU5UwgUp7CFNOJh1qM=
  on:
    tags: true
    repo: Hypheme/harmonized.js
