sudo: required
dist: trusty
language: node_js
node_js:
- '6'
cache:
  bundler: true
  directories:
  - node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install -g codecov
- npm install
script:
- npm run test:travis
- npm run eslint
after_success:
- npm run codecov
notifications:
  slack:
    secure: d5AQcOtE64iRta7beecYMeHWsyo9CRp8Wgt7gSsotMFFzMvkgwN1ZA981sVoaPdISxUntxktoEtCcrSdQgN5Ya6NcY4EAgnb+FBki8174VjGUHsSfW8gkeVKCIdd8vWGQagunrG/FVU3PRadgmhFTDPuSfFTYxnU+OHROPbncSQpF5rZblw16XQ0MVksGSbHIHza6wcPyfknk+2dqWrMPeHANpuVOrP5uiC8gFt1nIAYLmLHtsPro7csLN/VYQYWCQjJVzLE7B/E+q3suNBw0mV38XYMz9gHBCy7OQjIHB+UUEgO7ch4anfAF+NEmxGbyO7rInGDpPJaOxtcAQKNTEgUi9YZNm36Kdde7xvix1/ExAblgSBNug/4a1QPctfp6PWPAXNsTJoFkm0wVjWYT+FmKLvjYDJoJp6v2xBlOdh7x8AQuZC8HhiKisTJfkvrGx0UGTIFQdYbk1XB44jOI/t45IDN6My73FtqArc2wEZB2ZGMk83ExZ1XcPoRoA22hxOeQdSE1xWcAiaCq6zsd6YkJiRNEkw7aTZ3LH+tZ6y2pQJYlykYfEW4HRFkgRQoRXTLX+02WBTyvqVEKxbDX5p9Ee4N8eWBYU/TBkUdgOr+HyyleTCl4H+CXm/jctNNh7FAEBHlNdIzh8P1O/a1/71NUHgxRsnXyOd1xXsUYy4=
