codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 98%
        threshold: 4
        branches:
          - "*"
      pr:
        target: 98%
        threshold: 4
        branches: 'master'
        only_pulls: true
    patch:
      default:
        target: 98%
        threshold: 4
        branches: null
        only_pulls: true
    changes:
      default:
        enabled: yes
        branches: null
  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
