codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 90%
        threshold: 20
        branches: null
    patch:
      default:
        target: 96%
        threshold: 6
        branches: null
        only_pulls: true
    changes:
      default:
        branches: null
  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
